### ISSUE TITLE
Document proposal for managing unplanned work

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/bonnyci.org#53]
Add documentation to Lore describing a proposal for urgent unplanned work. Currently it is to create a new issue and label it as "Unplanned Work". If you are going to work on it then assign it to yourself and move to In Progress. If you are not going to work on it, then put it at the top of TODO. In either case bring it to the team's attention. Finally be sure to paste any IRC or email conversations as well as comments as you debug and discover (or don't discover) root cause.

**Comment by missaugustina** [comment]
- [x] Create label in Projman
- [x] Create Project Management section under developers/contributing in Lore
- [x] Add description from above

**Comment by SpamapS** [comment]
Looks done to me! Please re-open if I missed something.
